#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

echo "Launching roscore..."
roscore &
pid=$!
sleep 7s

echo "Launching Gazebo..."
roslaunch pioneer_gazebo frontier_exploration_world.launch &
pid="$pid $!"

sleep 8s

echo "Launching controller..."
roslaunch pioneer_ros pioneer_controller_spin_recover.launch &
pid="$pid $!"
sleep 7s

echo "Launching Rviz..."
roslaunch pioneer_description frontier_map.launch rviz_name:=pioneer &
pid="$pid $!"
sleep 7s


echo "Launching MAPPING..."
roslaunch pioneer_gazebo mapping.launch&
pid="$pid $!"

sleep 7s

echo "Launching MoveBase..."
rosrun move_base move_base \
    _name:=move_base \
    _global_costmap_params_file:=$(rospack find pioneer_2dnav)/global_costmap_params.yaml \
    _local_costmap_params_file:=$(rospack find pioneer_2dnav)/local_costmap_params.yaml \
    _base_local_planner_params_file:=$(rospack find pioneer_2dnav)/base_local_planner_params.yaml&
pid="$pid $!"


sleep 1s
rosbag record --all -o all_data&
sleep 2s 

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h
